### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by Lidilidian**
Mengubah bahasa dari English menjadi Indonesia.

### CODE REVIEW

**Comment by jayvdb** [comment]
I think it is important to include the official English text.
Unofficial translations may be added, but need to be *very* clearly described as not legally binding.

Also maybe translations should be in a special repo. c.f. https://github.com/steptr/MIT-License/issues/1

**Comment by jayvdb** [comment]
@Lidilidian , do you want to add your translation to https://github.com/steptr/MIT-License ; the repository has indicated they are willing to accept it if you follow the steps at https://github.com/steptr/MIT-License/issues/1 .

**Comment by Lidilidian** [comment]
done , check here https://github.com/steptr/MIT-License/pulls

2016-11-01 0:57 GMT+07:00 John Vandenberg <notifications@github.com>:

**Comment by juniorriau** [comment]
@Lidilidian Baik untuk official tetap akan english, untuk dokumentasi kita akan buatkan 2 versi, saat ini sedang pengerjaan kembalil untuk test alpha-2

**Comment by Lidilidian** [comment]
Oke ...

**Pull request closed without merging**
